import CountryDto from './CountryDto';
import { OrganizationDto } from './OrganizationDto';
import { ParentDto } from './ParentDto';
import StateDto from './StateDto';

export interface OnboardingParentDto {
  id: number;
  userId: string;
  email: string;
  username: string;
  timezoneId: string;
  profilePicture: string;
  organizationId: number;
  organization: OrganizationDto;
  dateOfBirth: Date;
  firstName: string;
  lastName: string;
  cellPhone: string | null;
  homePhone: string | null;
  chargeApplicationFee: boolean;
  chargeRegistrationFee: boolean;
  acceptTerms: boolean;
  employer: string | null;
  position: string | null;
  profession: string | null;
  jobTitle: string | null;
  workEmail: string | null;
  ssn: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  countryId: number | null;
  country: CountryDto | null;
  stateId: number | null;
  state: StateDto | null;
  city: string | null;
  zipcode: string | null;
  parentId: number | null;
  passwordUpdateRequiredForNewRegistration: boolean;
  registrationStatus: string | null;
  registrationCompletedDate: Date | null;
  temporaryPassword: string | null;
  mainParent: ParentDto | null;
  createdOn: Date;
  updatedOn: Date | null;
  isFullOnboarding: boolean;
  isEmergencyContact: boolean;
  croppedLicenseImage?:string;
  licenseNumber?: string;
  currentOnboardingStep?: number | null;
}
