import IAccountService from "./IAccountService";
import IHttpService from "./IHttpService";
import IUserService from "./IUserService";
import ICountryService from "./ICountryService";
import IStateService from "./IStateService";
import ILevelService from "./ILevelService";
import ISemesterService from "./ISemesterService";
import IErrorHandlerService from "./IErrorHandlerService";
import IOrganizationService from "./IOrganizationService";
import IJobTitleService from "./IJobTitleService";
import IHolidayTypeService from "./IHolidayTypeService";
import INotificationUrgencyService from "./INotificationUrgencyService";
import IAreaService from "./IAreaService";
import ITopicService from "./ITopicService";
import ILessonService from "./ILessonService";
import ISepAreaService from "./ISepAreaService";
import ISepLevelService from "./ISepLevelService";
import ISepTopicService from "./ISepTopicService";
import IStaffService from "./IStaffService";
import IPickupDropOffConfigurationService from "./IPickupDropOffConfigurationService";
import IUserRoleService from "./IUserRoleService";
import IPaymentMethodService from "./IPaymentMethodService";
import IOutsidePaymentMethodService from "./IOutsidePaymentMethodService";
import IDateTimeService from "./IDateTimeService";
import ISpecialFeeListService from "./ISpecialFeeListService";
import IInvoiceConfigurationService from "./IInvoiceConfigurationService";
import ISalaryTypeService from "./ISalaryTypeService";
import IProgramOptionService from "./IProgramOptionService";
import IAdditionalFeesService from "./IAdditionalFeesService";
import IPastDueFeesService from "./IPastDueFeesService";
import IRegistrationFeesService from "./IRegistrationFeesService";
import IClassService from "./IClassService";
import IEmploymentFormService from "./IEmploymentFormService";
import IEthnicityService from "./IEthnicityService";
import IDegreeService from "./IDegreeService";
import ICertificateService from "./ICertificateService";
import IBankAccountTypeService from "./IBankAccountTypeService";
import IStaffDegreeService from "./IStaffDegreeService";
import IStaffCertificationService from "./IStaffCertificationService";
import IStaffEmergencyContactService from "./IStaffEmergencyContactService";
import IStaffReferenceService from "./IStaffReferenceService";
import IStaffProfessionalDevelopmentService from "./IStaffProfessionalDevelopmentService";
import IStaffEmploymentHistoryService from "./IStaffEmploymentHistoryService";
import ITermsAndPolicyService from "./ITermsAndPolicyService";
import IParentService from "./IParentService";
import IStudentFormService from "./IStudentFormService";
import IEmailSettingService from "./IEmailSettingService";
import IStudentQuestionService from "./IStudentQuestionService";
import IEmailTemplateService from "./IEmailTemplateService";
import IStudentAllergyService from "./IStudentAllergyService";
import IStudentDentistService from "./IStudentDentistService";
import IStudentImmunizationService from "./IStudentImmunizationService";
import IStudentPhysicianService from "./IStudentPhysicianService";
import IStudentService from "./IStudentService";
import IStudentConsentAndQuestionForm from "./IStudentConsentAndQuestionForm";
import IPickupDropOffParentService from "./IPickupDropOffParentService";
import IPerformanceEvaluationSettingService from "./IPerformanceEvaluationSettingService";
import IPerformanceEvaluationQuestionService from "./IPerformanceEvaluationQuestionService";
import IStaffPerformanceEvaluationService from "./IStaffPerformanceEvaluationService";
import IPickUpDropOffStudentWiseService from "./IPickUpDropOffStudentWiseService";
import IReportService from "./IReportService";
import IClassAssignmentService from "./IClassAssignmentService";
import IStaffSchedulingService from "./IStaffSchedulingService";
import IStaffTimeTrackingService from "./IStaffTimeTracking";
import IClassAttendanceService from "./IClassAttendanceService";
import ILessonAssignmentService from "./ILessonAssignmentService";
import ISEPAssessmentService from "./ISEPAssessmentService";
import IParentBabyLogService from "./IParentBabyLogService";
import IRecordKeepingService from "./IRecordKeepingService";
import IHolidayService from "./IHolidayService";
import IDirectoryService from "./IDirectoryService";
import IEventService from "./IEventService";
import IPaymentConfigurationService from "./IPaymentConfigurationService";
import ICurrencyCodeService from "./ICurrencyCodeService";
import ISavedCardOrAchSrvice from "./ISavedCardOrAchSrvice";
import IInvoiceService from "./IInvoiceService";
import IRoleManagementService from "./IRoleManagementService";
import IDocuSignService from "./IDocuSignService";
import IRecurringInvoiceItemService from "./IRecurringInvoiceItemService";
import IParentInviteService from "./IParentInviteService";

export default interface IUnitOfService {
  HttpService: IHttpService;
  AccountService: IAccountService;
  UserService: IUserService;
  CountryService: ICountryService;
  StateService: IStateService;
  ErrorHandlerService: IErrorHandlerService;
  OrganizationService: IOrganizationService;
  JobTitleService: IJobTitleService;
  LevelService: ILevelService;
  SemesterService: ISemesterService;
  HolidayTypeService: IHolidayTypeService;
  NotificationUrgencyService: INotificationUrgencyService;
  AreaService: IAreaService;
  TopicService: ITopicService;
  LessonService: ILessonService;
  SepAreaService: ISepAreaService;
  SepLevelService: ISepLevelService;
  SepTopicService: ISepTopicService;
  StaffService: IStaffService;
  PickupDropOffConfigurationService: IPickupDropOffConfigurationService;
  UserRoleService: IUserRoleService;
  PaymentMethodService: IPaymentMethodService;
  OutsidePaymentMethodService: IOutsidePaymentMethodService;
  DateTimeService: IDateTimeService;
  SpecialFeeListService: ISpecialFeeListService;
  InvoiceConfigurationService: IInvoiceConfigurationService;
  SalaryTypeService: ISalaryTypeService;
  ProgramOptionService: IProgramOptionService;
  AdditionalFeesService: IAdditionalFeesService;
  PastDueFeesService: IPastDueFeesService;
  RegistrationFeesService: IRegistrationFeesService;
  ClassService: IClassService;
  EmploymentFormService: IEmploymentFormService;
  EthnicityService: IEthnicityService;
  DegreeService: IDegreeService;
  CertificateService: ICertificateService;
  BankAccountTypeService: IBankAccountTypeService;
  StaffDegreeService: IStaffDegreeService;
  StaffCertificationService: IStaffCertificationService;
  StaffEmergencyContactService: IStaffEmergencyContactService;
  StaffReferenceService: IStaffReferenceService;
  StaffProfessionalDevelopmentService: IStaffProfessionalDevelopmentService;
  StaffEmploymentHistoryService: IStaffEmploymentHistoryService;
  TermsAndPolicyService: ITermsAndPolicyService;
  ParentService: IParentService;
  StudentFormService: IStudentFormService;
  EmailSettingService: IEmailSettingService;
  StudentQuestionService: IStudentQuestionService;
  EmailTemplateService: IEmailTemplateService;
  StudentAllergyService: IStudentAllergyService;
  StudentDentistService: IStudentDentistService;
  StudentImmunizationService: IStudentImmunizationService;
  StudentPhysicianService: IStudentPhysicianService;
  StudentService: IStudentService;
  ParentInviteService: IParentInviteService;
  StudentConsentAndQuestionForm: IStudentConsentAndQuestionForm;
  PickupDropoffParentService: IPickupDropOffParentService;
  PerformanceEvaluationSettingService: IPerformanceEvaluationSettingService;
  PerformanceEvaluationQuestionService: IPerformanceEvaluationQuestionService;
  StaffPerformanceEvaluationService: IStaffPerformanceEvaluationService;
  PickUpDropOffStudentWiseService: IPickUpDropOffStudentWiseService;
  ReportService: IReportService;
  ClassAssignmentService: IClassAssignmentService;
  StaffSchedulingService: IStaffSchedulingService;
  StaffTimeTrackingService: IStaffTimeTrackingService;
  ClassAttendanceService: IClassAttendanceService;
  LessonAssignmentService: ILessonAssignmentService;
  SEPAssessmentService: ISEPAssessmentService;
  ParentBabyLogService: IParentBabyLogService;
  RecordKeepingService: IRecordKeepingService;
  HolidayService: IHolidayService;
  DirectoryService: IDirectoryService;
  EventService: IEventService;
  PaymentConfigurationService: IPaymentConfigurationService;
  CurrencyCodeService: ICurrencyCodeService;
  SavedCardOrAchSrvice: ISavedCardOrAchSrvice;
  InvoiceService: IInvoiceService;
  RoleManagementService: IRoleManagementService;
  DocuSignService: IDocuSignService;
  RecurringInvoiceItemService: IRecurringInvoiceItemService;
}
